"""Monitoring and Alert models."""
from datetime import datetime, timezone
from sqlalchemy import Boolean, DateTime, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from nova_app.db.base import Base


class SystemMetricsSnapshot(Base):
    """Periodic hardware metrics snapshot."""
    __tablename__ = "system_metrics_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
        nullable=False
    )
    cpu_pct: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    ram_pct: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    gpu_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    disk_pct: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    net_sent_kb: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    net_recv_kb: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    battery_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    temperature_c: Mapped[float | None] = mapped_column(Float, nullable=True)


class SystemAlert(Base):
    """Threshold alerts generated by system event watchers."""
    __tablename__ = "system_alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    alert_type: Mapped[str] = mapped_column(String(64), nullable=False)  # high_cpu, low_battery, usb_connected, etc.
    message: Mapped[str] = mapped_column(String(512), nullable=False)
    acknowledged: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
